### ISSUE TITLE
Hackintool 3.7.5 no longer autodetects Clover as bootloader?

### ISSUE THREAD

**Issue by mackonsti** [headkaze/Hackintool#161] opened 2021-12-04 11:34 UTC
Hello @headkaze thanks once more for all your latest work and updates!

I have just updated to Hackintool 3.7.5 and I see that Clover is not recognised but only OpenCore is shown. This was working before, obviously.

First of all, I am installing Clover or OpenCore manually in the EFI partition by copying a working folder/configuration. This means that I am not using an installer, hence when Hackintool tries to find that plist file installed on the system (the name escapes me now) the version is shown as 0.0.0 for **Current Booted Version** which is to be expected.

But for the field **Name** how do you detect the bootloader of the system? Is it again via some file registered on the system drive/partition, too?

I don't want to bother you too much with this as it may seem minor but this used to work, to be honest. When I manually select "Clover" I do get the detected version r5142.

Please can you kindly provide the method of obtaining the **Name** and **Current Booted Version** fields, for information?

Perhaps consider replacing **"0.0.0"** and **"0"** with the words **"Not Registered"** which is better and more clear to the user?
![Hackintool_Bootloader](https://user-images.githubusercontent.com/1313613/144707726-8cbba23c-dcf8-48ec-9ba7-dde351e671df.png)
![Hackintool_Clover](https://user-images.githubusercontent.com/1313613/144707891-6c7bae52-0e9e-46b0-b97b-cd43af5e322a.png)
Warm thanks.

**Comment by headkaze** [comment] 2021-12-08 01:41
Hackintool will do the following:

1. Check for IODeviceTree:/efi/platform/clovergui-revision
2. Check for IODeviceTree:/options/4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version

Once it detects OpenCore it will consider it an OpenCore booted system. The only way to change it is to clear NVRAM so the version entry made by OpenCore is removed.

**Comment by mackonsti** [comment] 2021-12-11 10:17
Hello @headkaze thank you for your feedback and reply. I rebooted and did clear NVRAM via F11 in Clover boot menu, and still cannot autodetect it.

```
ioreg -p IODeviceTree -l efi | grep clovergui-revision
    |       "clovergui-revision" = <16140000>
```

I tried searching `options` and `opencore` but no output from `ioreg -p IODeviceTree -l options | grep opencore-version`

Any ideas? (perhaps my search string is wrong for OpenCore?)
![efi-platform-clovergui-revision](https://user-images.githubusercontent.com/1313613/145672836-932010d6-a3fd-4df0-aec2-c2c6bb1ea19c.png)
Thank you

**Comment by headkaze** [comment] 2021-12-11 19:48
It's a hidden IOReg entry. Try running the attached app.
[ocver.zip](https://github.com/headkaze/Hackintool/files/7697657/ocver.zip)

**Comment by mackonsti** [comment] 2021-12-11 21:53
Hi mate, here is the result of the command; could this be a Clover problem?
```
% ./ocver 
UNK-000-0000-00-00
```
On my other Big Sur (Intel NUC) Hackintosh with OpenCore, the output gives correct result:
```
% ./ocver 
REL-075-2021-11-02
```

**Comment by headkaze** [comment] 2021-12-12 15:39
Okay so I looked this up and you can just run the following:
`nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version`
You can try to delete the variable by running
`nvram -d 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version`

**Comment by mackonsti** [comment] 2021-12-14 20:25
Good evening apologies for my late reply. So indeed something is stored in that variable on NVRAM. I guess this is a possible remnant from my attempts to boot from a USB stick with a possible OpenCore boot configuration:

```
% nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version
4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version	UNK-000-0000-00-00
```

I will delete the variable, reboot and update my message here.

**Comment by mackonsti** [comment] 2021-12-18 15:36
Hello @headkaze I would like to report a couple of things for you when you have some free time to check this out. I tested this on my other NUC and there seems to be some consistency... in the problem 😄 

a) First of all, there seems to be an issue getting the latest version of Clover online, can you please check this? I don't seem to get the popup prompting me to update, problem in the URL?

b) For some unknown reason yet, I suspect that some modules or other code from Clover is injecting this "zero" version of open-core as some parts/quirks/tweaks were copied over. This means that this NVRAM above parameter is injected by Clover. It happens on r5142 and **not** on r5139. I reported it on the respective thread just now.

Moreover, I was told from in the OpenCore thread that this parameter is injected in RAM and not saved, this is why I cannot seem to be able to delete it (but thanks again for your help).

c) Despite rebooting on r5139 without this "opencore-version" in RAM/NVRAM, the auto-update seems to find the correct booted version:
```
% ioreg -p IODeviceTree -l efi | grep clovergui-revision   
    |       "clovergui-revision" = <13140000>
```
However, the last installed version still reports 0.0.0. Is Hackintool looking for some PLIST file that the Clover installer was/is creating? I cannot remember the path nor the file name that Clover installer was creating but I do suggest for the clarity of information for people, to replace the 0.0.0 with something more friendly like **"No Clover package installation detected"** -- what do you think?

d) Perhaps it is wise to create a further check for OpenCore that the **fist 3 digits** are not `UNK` or are at least `REL` to denote a release, no? I refer to the value `UNK-000-0000-00-00` that is not sure if it will be fixed or not (in Clover) and thus won't get Hackintool confused with this whole issue we discuss here.

Thanks in advance for the checks on the issues above, your feedback is always appreciated.

![Clover-Not-Detected](https://user-images.githubusercontent.com/1313613/146646500-8fe3aa51-d004-4bff-b793-5a245753a864.png)

**Comment by headkaze** [comment] 2021-12-18 15:53
Please check out 3.7.9 and let me know if it detects Clover correctly now.

**Comment by SRSaunders** [comment] 2021-12-18 16:31
I can confirm that Clover detection (v5142) now works properly with 3.7.9.  Thanks for fixing.

I presume you can no longer get the Latest Available Clover Version due to GitHib policy changes (i.e. same as CloverUpdater).

**Comment by mackonsti** [comment] 2021-12-18 17:47
Hi @headkaze thanks for fixing this, indeed it detects r5142 now. Appreciate it.

I was not aware of GitHub policy changes, shame we can't get this, thanks @SRSaunders but how does it work for acidanthera's kexts still ?

Finally @headkaze kindly consider replacing the zero/zeros in the "Last Installed Version" with `No Clover package installation detected` that way people understand it's the package installed that's **not** detected, not booting... (you never know). Thank you!

**Comment by headkaze** [comment] 2021-12-18 18:50
Please check out 3.8.0. Clover version detection should be fixed.

**Comment by SRSaunders** [comment] 2021-12-18 19:38
Great!  Thanks for fixing the Clover version checking as well - 3.8.0 works.

**Comment by mackonsti** [comment] 2021-12-18 22:10
I confirm @headkaze thank you for taking the time to fix this. Ticket can close. Season greetings

**Closed** 2021-12-21 01:19 UTC
